/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package telas;

/**
 *
 * @author ecardoso
 */
import dao.AcomodacaoDAO;
import dao.HotelDAO;
import dao.ReservaDAO;
import dao.UtilizadoresDAO;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import model.Funcionario;
import model.Hotel;
import model.Reserva;
import model.Utilizadores;
import model.acomodacao.Acomodacao;
import model.acomodacao.QuartoSimples;
import model.acomodacao.SuitePresidencial;
import services.LoginService;
import util.SessionManager;



public class ReservaGuest extends javax.swing.JInternalFrame {
  private JLabel tipoLabel;
    private JLabel leitosLabel;
    private JLabel precoLabel;
    private JTextField tipoField;
    private JTextField leitosField;
    private JTextField precoField;
    private JButton adicionarButton;
    private JButton atualizarButton;
    private JButton excluirButton;
    String username;
    private LoginService loginService;
    /**
     * Creates new form TelaAcomodacao
     */
    public ReservaGuest(LoginService loginService) {
        this.loginService = loginService;
        initComponents();
        atualizarTabelaReservas();
        
    }
    
    
    private void atualizarTabelaReservas() {
    HotelDAO hotelDAO = new HotelDAO();
        List<Object[]> hoteis = hotelDAO.buscarTodosHoteis();

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Limpa a tabela antes de adicionar os resultados

        for (Object[] hotel : hoteis) {
            model.addRow(hotel);
        }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtIdLocalizacaoHotel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnReservar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        DateCheckout = new com.toedter.calendar.JDateChooser();
        DateCheckin = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();

        setClosable(true);

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hotel", "Localização", "Acomodação", "Nº de camas", "Preço"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Data Check-Out");

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        jLabel3.setText("Localização");

        btnReservar.setText("Reservar");
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Encontre a sua próxima estadia");

        jLabel6.setText("Data Check-In");

        jLabel8.setText("Pesquise ofertas em hotéis, casas e muito mais...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdLocalizacaoHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(DateCheckin, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(DateCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(btnPesquisar))))
                            .addComponent(btnReservar, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(91, 91, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdLocalizacaoHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DateCheckin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DateCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnPesquisar))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReservar)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
     String localizacao = txtIdLocalizacaoHotel.getText().trim();

    // Obter as datas de check-in e check-out dos componentes de data
    java.util.Date utilDateCheckin = DateCheckin.getDate();
    java.util.Date utilDateCheckout = DateCheckout.getDate();

    // Verificar se as datas estão selecionadas
    if (localizacao.isEmpty() || utilDateCheckin == null || utilDateCheckout == null) {
        JOptionPane.showMessageDialog(this, "Por favor, insira uma localização e selecione as datas de check-in e check-out.");
        return;
    }

    // Converter java.util.Date para java.sql.Date
    java.sql.Date sqlDateCheckin = new java.sql.Date(utilDateCheckin.getTime());
    java.sql.Date sqlDateCheckout = new java.sql.Date(utilDateCheckout.getTime());

    // Chamar o método buscarHoteisDisponiveisPorData no HotelDAO
    HotelDAO hotelDAO = new HotelDAO();
    List<Object[]> hoteis = hotelDAO.buscarHoteisDisponiveisPorData(localizacao, sqlDateCheckin, sqlDateCheckout);

    // Atualizar a tabela com os resultados
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0); // Limpa a tabela antes de adicionar os resultados

    if (hoteis.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Nenhum hotel disponível encontrado para a localização e datas especificadas.");
    } else {
        for (Object[] hotel : hoteis) {
            model.addRow(hotel);
        }
    }
    }//GEN-LAST:event_btnPesquisarActionPerformed



    
    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
            // Obtém o índice da linha selecionada
    int rowIndex = jTable1.getSelectedRow();

    // Verifica se uma linha foi realmente selecionada
    if (rowIndex != -1) {
        // Obtém os dados da reserva selecionada
        int idReserva = (int) jTable1.getValueAt(rowIndex, 0);
        int idCliente = (int) jTable1.getValueAt(rowIndex, 1);
        int idHotel = (int) jTable1.getValueAt(rowIndex, 2);
        int idAcomodacao = (int) jTable1.getValueAt(rowIndex, 3);
        Date dataCheckin = (Date) jTable1.getValueAt(rowIndex, 4);
        Date dataCheckout = (Date) jTable1.getValueAt(rowIndex, 5);

       
        txtIdLocalizacaoHotel.setText(String.valueOf(idHotel));
        DateCheckin.setDate(dataCheckin);
        DateCheckout.setDate(dataCheckout);
    }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed
          
       // Verifica se o usuário está logado
    if (!SessionManager.isLoggedIn()) {
        JOptionPane.showMessageDialog(this, "Por favor, faça login para continuar.");
        // Abre a tela de login
        TelaLogin telaLogin = new TelaLogin(loginService);
        telaLogin.setVisible(true);
        return;
    }
        int linhaSelecionada = jTable1.getSelectedRow();
    if (linhaSelecionada == -1) {
        JOptionPane.showMessageDialog(this, "Selecione uma reserva para excluir.");
        return;
    }

    int idReserva = (int) jTable1.getValueAt(linhaSelecionada, 0);
    if (JOptionPane.showConfirmDialog(this, "Deseja realmente excluir esta reserva?", "Confirmar exclusão", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
        ReservaDAO reservaDAO = new ReservaDAO();
        if (reservaDAO.excluirReserva(idReserva)) {
            JOptionPane.showMessageDialog(this, "Reserva excluída com sucesso!");
            atualizarTabelaReservas();
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao excluir reserva.");
        }
    }
    }//GEN-LAST:event_btnReservarActionPerformed
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateCheckin;
    private com.toedter.calendar.JDateChooser DateCheckout;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnReservar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtIdLocalizacaoHotel;
    // End of variables declaration//GEN-END:variables
}
