/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package telas;

/**
 *
 * @author ecardoso
 */
import dao.AcomodacaoDAO;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.acomodacao.Acomodacao;
import model.acomodacao.QuartoSimples;
import model.acomodacao.SuitePresidencial;



public class TelaAcomodacao extends javax.swing.JInternalFrame {
  private JLabel tipoLabel;
    private JLabel leitosLabel;
    private JLabel precoLabel;
    private JTextField tipoField;
    private JTextField leitosField;
    private JTextField precoField;
    private JButton adicionarButton;
    private JButton atualizarButton;
    private JButton excluirButton;
    /**
     * Creates new form TelaAcomodacao
     */
    public TelaAcomodacao() {
        initComponents();
        atualizarTabelaAcomodacoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtNumeroCama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ComboBoxTipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        TextFieldPreco = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNumeroQuarto1 = new javax.swing.JTextField();
        btnAtualizar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtHotelId = new javax.swing.JTextField();

        setClosable(true);

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id ", "Tipo", "Camas", "Preço", "Hotel id"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Id");

        jLabel2.setText("Tipo de Acomodação");

        ComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Simples", "Presidencial" }));
        ComboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxTipoActionPerformed(evt);
            }
        });

        jLabel4.setText("Preço");

        jButton1.setText("Adicionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        jButton2.setText("Excluir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Gestão de Acomodações");

        jLabel6.setText("Camas");

        jLabel7.setText("Id hotel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(btnAtualizar)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtHotelId, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TextFieldPreco, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNumeroCama, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ComboBoxTipo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtNumeroQuarto1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNumeroQuarto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtNumeroCama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addGap(4, 4, 4)
                        .addComponent(txtHotelId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(btnAtualizar))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  try {
        // Coletar dados dos campos de texto
        String tipoQuarto = ComboBoxTipo.getSelectedItem().toString(); // Tipo de quarto (Simples ou Presidencial)
        int numeroQuarto = Integer.parseInt(txtNumeroQuarto1.getText());
        int quantidadeLeitos = Integer.parseInt(txtNumeroCama.getText()); // Número de camas
        double precoBase = Double.parseDouble(TextFieldPreco.getText());
        int hotelid = Integer.parseInt(txtHotelId.getText()); // ID do hotel

        // Verificar se já existe uma acomodação com a mesma quantidade de leitos e mesmo hotel
        AcomodacaoDAO acomodacaoDAO = new AcomodacaoDAO();
        if (acomodacaoDAO.existeAcomodacaoPorQuantidadeLeitos(quantidadeLeitos, hotelid)) {
            JOptionPane.showMessageDialog(this, "Já existe uma acomodação com a mesma quantidade de leitos neste hotel. Por favor, verifique os dados.", "Erro ao adicionar acomodação", JOptionPane.ERROR_MESSAGE);
            return; // Sai do método sem adicionar a acomodação
        }

        // Criar uma nova instância de Acomodacao com base no tipo de quarto selecionado
        Acomodacao novaAcomodacao;
        if (tipoQuarto.equals("Simples")) {
            novaAcomodacao = new QuartoSimples(numeroQuarto, tipoQuarto, quantidadeLeitos, precoBase, hotelid);
        } else if (tipoQuarto.equals("Presidencial")) {
            novaAcomodacao = new SuitePresidencial(numeroQuarto, tipoQuarto, quantidadeLeitos, precoBase, hotelid);
        } else {
            // Lidar com tipos de quarto desconhecidos
            System.out.println("Tipo de quarto desconhecido: " + tipoQuarto);
            return;
        }

        // Definir quantidade de leitos e outros atributos
        novaAcomodacao.setQuantidadeLeitos(quantidadeLeitos);
        novaAcomodacao.setPrecoBase(precoBase);
        novaAcomodacao.setId(numeroQuarto);
        novaAcomodacao.setTipo(tipoQuarto);
        novaAcomodacao.setIdHotel(hotelid);

        // Inserir acomodação no banco de dados
        acomodacaoDAO.inserirAcomodacao(novaAcomodacao);
        JOptionPane.showMessageDialog(this, "Acomodação criada com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

        // Limpar campos após a inserção
        limparCampos();

        // Atualizar tabela de acomodações
        atualizarTabelaAcomodacoes();

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Por favor, insira valores válidos para o número do quarto, número de camas ou preço.", "Erro de Formato", JOptionPane.ERROR_MESSAGE);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Erro ao adicionar acomodação: " + e.getMessage(), "Erro de SQL", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Ocorreu um erro ao adicionar a acomodação: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void atualizarTabelaAcomodacoes() {
    // Limpar tabela
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);
    
    // Obter todas as acomodações do banco de dados
    AcomodacaoDAO acomodacaoDAO = new AcomodacaoDAO();
    List<Acomodacao> acomodacoes = acomodacaoDAO.obterTodasAcomodacoes();

    // Preencher tabela com as acomodações obtidas
    for (Acomodacao acomodacao : acomodacoes) {
        Object[] rowData = {acomodacao.getId(), acomodacao.getTipo(),acomodacao.getQuantidadeLeitos(), acomodacao.getPrecoBase(),acomodacao.getIdHotel()};
        model.addRow(rowData);
    }
}

    
    private void ComboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxTipoActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // Obter a linha selecionada
    int rowIndex = jTable1.getSelectedRow();

    // Verificar se uma linha foi selecionada
    if (rowIndex != -1) {
        // Obter os dados da linha selecionada
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int id = (int) model.getValueAt(rowIndex, 0);
        String tipo = (String) model.getValueAt(rowIndex, 1);
        int quantidadeLeitos = (int) model.getValueAt(rowIndex, 2);
        double precoBase = (double) model.getValueAt(rowIndex, 3);
        int idhotel=(int) model.getValueAt(rowIndex, 4);

        // Preencher os campos de texto com os dados da acomodação selecionada
        txtNumeroQuarto1.setText(Integer.toString(id));
        ComboBoxTipo.setSelectedItem(tipo);
        txtNumeroCama.setText(Integer.toString(quantidadeLeitos));
        TextFieldPreco.setText(Double.toString(precoBase));
        txtHotelId.setText(Integer.toString(idhotel));
    }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
               // Coletar dados dos campos de texto
    String tipoQuarto = ComboBoxTipo.getSelectedItem().toString();
    int numeroQuarto = Integer.parseInt(txtNumeroQuarto1.getText());
    int quantidadeLeitos = Integer.parseInt(txtNumeroCama.getText());
    double precoBase = Double.parseDouble(TextFieldPreco.getText());
    int idhotel=Integer.parseInt(txtHotelId.getText());

    // Criar uma instância de Acomodacao com base no tipo de quarto selecionado
    Acomodacao acomodacao;
    if (tipoQuarto.equals("Simples")) {
        acomodacao = new QuartoSimples(numeroQuarto, tipoQuarto, quantidadeLeitos, precoBase,idhotel);
    } else if (tipoQuarto.equals("Presidencial")) {
        acomodacao = new SuitePresidencial(numeroQuarto, tipoQuarto, quantidadeLeitos, precoBase,idhotel);
    } else {
        JOptionPane.showMessageDialog(TelaAcomodacao.this, "Tipo de quarto desconhecido: " + tipoQuarto);
        return;
    }

    // Atualizar acomodação no banco de dados
    AcomodacaoDAO acomodacaoDAO = new AcomodacaoDAO();
    acomodacaoDAO.atualizarAcomodacao(acomodacao);
    JOptionPane.showMessageDialog(TelaAcomodacao.this, "Acomodação atualizada!");

    // Atualizar tabela
    atualizarTabelaAcomodacoes();
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           // Coletar o ID da acomodação
    int numeroQuarto = Integer.parseInt(txtNumeroQuarto1.getText());

    // Excluir acomodação do banco de dados
    AcomodacaoDAO acomodacaoDAO = new AcomodacaoDAO();
    acomodacaoDAO.excluirAcomodacao(numeroQuarto);
    JOptionPane.showMessageDialog(TelaAcomodacao.this, "Acomodação excluída!");

    // Atualizar tabela
    atualizarTabelaAcomodacoes();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxTipo;
    private javax.swing.JTextField TextFieldPreco;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtHotelId;
    private javax.swing.JTextField txtNumeroCama;
    private javax.swing.JTextField txtNumeroQuarto1;
    // End of variables declaration//GEN-END:variables

    private void limparCampos() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
